/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.gameshop.view.rental;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import py.edu.fiuni.gameshop.controller.rental.GameSelectController;
import py.edu.fiuni.gameshop.dao.mysql.DAOConnection;
import py.edu.fiuni.gameshop.dao.mysql.MySQLGameDAO;

/*
 *UNIVERSIDAD NACIONAL DE ITAPUA
 *PROJECT GAMESHOP
 *
 * 2020 - SEGUNDO SEMESTRE
 *
 *  Jorge Tyrakowski & Pamela Horn
 */

/**
 * This class contains the window to select a game manually
 */
public class GameSelect extends javax.swing.JFrame {

    private MySQLGameDAO dao;
    private DAOConnection connection;
    private GameSelectController controller;
    public PanelRental panel;
    public String selectedGame = "";

    /**
     * Constructor where the necessary for the use of the panel is initialized.
     */
    public GameSelect(PanelRental panel) {
        initComponents();
        this.setSize(1280, 650);
        this.setPreferredSize(new Dimension(1280, 650));
        setLocationRelativeTo(null);
        this.setVisible(true);
        this.connection = new DAOConnection();
        this.dao = new MySQLGameDAO(connection);
        this.panel = panel;
        this.controller = new GameSelectController(this, dao);
        consultTable();
        addListeners();

    }

    /**
     * Method in charge of adding the listeners
     */
    private void addListeners() {
        this.jbttSelect.addActionListener(controller);
        this.jbttSeeMore.addActionListener(controller);
    }

    /**
     * Method in charge of updating the table by consulting the information in
     * the database.
     */
    private void consultTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            this.tblGamesTable.setModel(model);

            Connection con = this.connection.getConexion();
            PreparedStatement ps = null;
            ResultSet rs = null;

            String SELECT = "SELECT name, console, price, availability FROM games";
            ps = con.prepareStatement(SELECT);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int columnsCant = rsMd.getColumnCount();

            model.addColumn("GAME");
            model.addColumn("CONSOLE");
            model.addColumn("PRICE");
            model.addColumn("STATE");

            while (rs.next()) {

                Object[] rows = new Object[columnsCant];

                for (int i = 0; i < columnsCant; i++) {
                    if (i == 3) {
                        if (rs.getBoolean(i + 1)) {
                            rows[i] = "Available";
                        } else {
                            rows[i] = "Non available";
                        }
                    } else {
                        rows[i] = rs.getObject(i + 1);
                    }
                }

                model.addRow(rows);

            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * Update the game table.
     */
    public void update() {
        consultTable();
    }

    public String getSelectedGame() {
        return this.selectedGame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlMain = new javax.swing.JPanel();
        jpnlMenu = new javax.swing.JPanel();
        pnlUp = new javax.swing.JPanel();
        pnlDown = new javax.swing.JPanel();
        jbttSeeMore = new javax.swing.JButton();
        jbttSelect = new javax.swing.JButton();
        spnlTable = new javax.swing.JScrollPane();
        tblGamesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 630));

        jpnlMain.setLayout(new java.awt.BorderLayout());

        jpnlMenu.setOpaque(false);
        jpnlMenu.setPreferredSize(new java.awt.Dimension(1280, 630));
        jpnlMenu.setRequestFocusEnabled(false);
        jpnlMenu.setLayout(new java.awt.BorderLayout());

        pnlUp.setBackground(new java.awt.Color(60, 17, 17));
        pnlUp.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout pnlUpLayout = new javax.swing.GroupLayout(pnlUp);
        pnlUp.setLayout(pnlUpLayout);
        pnlUpLayout.setHorizontalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
        );
        pnlUpLayout.setVerticalGroup(
            pnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpnlMenu.add(pnlUp, java.awt.BorderLayout.PAGE_START);

        pnlDown.setBackground(new java.awt.Color(60, 17, 17));

        jbttSeeMore.setBackground(new java.awt.Color(255, 255, 255));
        jbttSeeMore.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbttSeeMore.setForeground(new java.awt.Color(0, 0, 0));
        jbttSeeMore.setText("SEE MORE");

        jbttSelect.setBackground(new java.awt.Color(255, 255, 255));
        jbttSelect.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbttSelect.setForeground(new java.awt.Color(0, 0, 0));
        jbttSelect.setText("SELECT");

        javax.swing.GroupLayout pnlDownLayout = new javax.swing.GroupLayout(pnlDown);
        pnlDown.setLayout(pnlDownLayout);
        pnlDownLayout.setHorizontalGroup(
            pnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDownLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbttSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbttSeeMore)
                .addContainerGap(801, Short.MAX_VALUE))
        );
        pnlDownLayout.setVerticalGroup(
            pnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDownLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttSeeMore)
                    .addComponent(jbttSelect))
                .addGap(38, 38, 38))
        );

        jpnlMenu.add(pnlDown, java.awt.BorderLayout.PAGE_END);

        spnlTable.setBackground(new java.awt.Color(0, 0, 0));
        spnlTable.setForeground(new java.awt.Color(0, 0, 0));
        spnlTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spnlTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spnlTable.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        spnlTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnlTableMouseClicked(evt);
            }
        });

        tblGamesTable.setBackground(new java.awt.Color(255, 255, 255));
        tblGamesTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblGamesTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblGamesTable.setForeground(new java.awt.Color(0, 0, 0));
        tblGamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GAME", "CONSOLE", "PRICE", "STATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGamesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblGamesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblGamesTable.setGridColor(new java.awt.Color(0, 0, 0));
        tblGamesTable.setRowHeight(20);
        tblGamesTable.setSelectionBackground(new java.awt.Color(60, 17, 17));
        tblGamesTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblGamesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGamesTableMouseClicked(evt);
            }
        });
        spnlTable.setViewportView(tblGamesTable);

        jpnlMenu.add(spnlTable, java.awt.BorderLayout.CENTER);

        jpnlMain.add(jpnlMenu, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jpnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is in charge of saving the information of the selected row
     */
    private void tblGamesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGamesTableMouseClicked
        int row = this.tblGamesTable.rowAtPoint(evt.getPoint());
        this.selectedGame = String.valueOf(this.tblGamesTable.getValueAt(row, 0));
    }//GEN-LAST:event_tblGamesTableMouseClicked

    private void spnlTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnlTableMouseClicked

    }//GEN-LAST:event_spnlTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbttSeeMore;
    public javax.swing.JButton jbttSelect;
    private javax.swing.JPanel jpnlMain;
    private javax.swing.JPanel jpnlMenu;
    private javax.swing.JPanel pnlDown;
    private javax.swing.JPanel pnlUp;
    private javax.swing.JScrollPane spnlTable;
    private javax.swing.JTable tblGamesTable;
    // End of variables declaration//GEN-END:variables
}
