/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.gameshop.view.rental;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import py.edu.fiuni.gameshop.controller.rental.GameSelectController;
import py.edu.fiuni.gameshop.controller.rental.RentalController;
import py.edu.fiuni.gameshop.dao.mysql.DAOConnection;
import py.edu.fiuni.gameshop.dao.mysql.MySQLClientDAO;
import py.edu.fiuni.gameshop.dao.mysql.MySQLGameDAO;
import py.edu.fiuni.gameshop.dao.mysql.MySQLPolicyDAO;
import py.edu.fiuni.gameshop.dao.mysql.MySQLRentalDAO;
import py.edu.fiuni.gameshop.dao.mysql.MySQLRentalDetailDAO;
import py.edu.fiuni.gameshop.model.Client;
import py.edu.fiuni.gameshop.model.Game;

/*
 *UNIVERSIDAD NACIONAL DE ITAPUA
 *PROJECT GAMESHOP
 *
 * 2020 - SEGUNDO SEMESTRE
 *
 *  Jorge Tyrakowski & Pamela Horn
 */

/**
 * This class contains the panel for video game rentals.
 */
public class PanelRental extends javax.swing.JPanel {

    private RentalController controller;
    private MySQLClientDAO cdao;
    private MySQLGameDAO gdao;
    private MySQLRentalDAO rdao;
    private MySQLRentalDetailDAO rddao;
    private MySQLPolicyDAO pdao;
    private DAOConnection connection;
    private GameSelectController gameManuallySearch;

    private Client client;
    private String clientSelected;
    private Game game;
    private Date returnDate;
    private int daysToRent;
    private double totalCost;

    /**
     * Constructor where the necessary for the use of the panel is initialized.
     */
    public PanelRental() {
        initComponents();
        this.connection = new DAOConnection();
        this.cdao = new MySQLClientDAO(connection);
        this.gdao = new MySQLGameDAO(connection);
        this.rdao = new MySQLRentalDAO(connection);
        this.pdao = new MySQLPolicyDAO(connection);
        this.rddao = new MySQLRentalDetailDAO(connection);
        this.controller = new RentalController(this, cdao, gdao, pdao, rdao, rddao);
        this.clientSelected = "";
        consultTable();
        addListeners();
        this.daysToRent = 0;
    }

    /**
     * Method in charge of adding the listeners
     */
    private void addListeners() {
        this.jbttClientSearch.addActionListener(controller);
        this.jbttGameSearch.addActionListener(controller);
        this.jbttBack.addActionListener(controller);
        this.jbttTotal.addActionListener(controller);
        this.jbttConfirm.addActionListener(controller);
        this.jbttConfirmDaysToRent.addActionListener(controller);

    }

    /**
     * Method in charge of updating the table by consulting the information in
     * the database.
     */
    private void consultTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            this.tableRent.setModel(model);

            Connection con = this.connection.getConexion();
            PreparedStatement ps = null;
            ResultSet rs = null;

            String SELECT = "SELECT gameName, clientName, saleDate, returnDate FROM rental WHERE clientName=?";
            ps = con.prepareStatement(SELECT);
            ps.setString(1, clientSelected);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int columnsCant = rsMd.getColumnCount();

            model.addColumn("GAME");
            model.addColumn("CLIENT");
            model.addColumn("SALE");
            model.addColumn("DATE");

            while (rs.next()) {

                Object[] rows = new Object[columnsCant];

                for (int i = 0; i < columnsCant; i++) {
                    rows[i] = rs.getObject(i + 1);
                }

                model.addRow(rows);

            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * Update the game table.
     */
    public void update() {
        consultTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbttBack = new javax.swing.JButton();
        jpnlMenu = new javax.swing.JPanel();
        jlblClientDNI = new javax.swing.JLabel();
        jlblGameName = new javax.swing.JLabel();
        jlblClient = new javax.swing.JLabel();
        txtGameSearch = new javax.swing.JTextField();
        jbttClientSearch = new javax.swing.JButton();
        txtGame = new javax.swing.JTextField();
        jbttGameSearch = new javax.swing.JButton();
        jlblGame = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jlblState = new javax.swing.JLabel();
        txtClientDNISearch = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtClientNameSurname = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jlblTable = new javax.swing.JLabel();
        jlblClientDebts = new javax.swing.JLabel();
        txtDebts = new javax.swing.JTextField();
        jlbDaysToRent = new javax.swing.JLabel();
        txtDaysToRent = new javax.swing.JTextField();
        jbttConfirmDaysToRent = new javax.swing.JButton();
        jpnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRent = new javax.swing.JTable();
        jpnlDown = new javax.swing.JPanel();
        jbttCancel = new javax.swing.JButton();
        jbttConfirm = new javax.swing.JButton();
        jbttTotal = new javax.swing.JButton();
        txtTotalCost = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jpnlUp.setBackground(new java.awt.Color(51, 0, 0));
        jpnlUp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CheckPoint");

        jbttBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/gameshop/view/icons/mini-icons/return.png"))); // NOI18N
        jbttBack.setContentAreaFilled(false);
        jbttBack.setOpaque(false);
        jbttBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlUpLayout = new javax.swing.GroupLayout(jpnlUp);
        jpnlUp.setLayout(jpnlUpLayout);
        jpnlUpLayout.setHorizontalGroup(
            jpnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlUpLayout.createSequentialGroup()
                .addComponent(jbttBack)
                .addGap(421, 421, 421)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlUpLayout.setVerticalGroup(
            jpnlUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlUpLayout.createSequentialGroup()
                .addComponent(jbttBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpnlMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblClientDNI.setBackground(new java.awt.Color(0, 0, 0));
        jlblClientDNI.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblClientDNI.setText("Client D.N.I. :");

        jlblGameName.setBackground(new java.awt.Color(0, 0, 0));
        jlblGameName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblGameName.setText("Game name :");

        jlblClient.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblClient.setText("Client :");

        txtGameSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtGameSearch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtGameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGameSearchActionPerformed(evt);
            }
        });

        jbttClientSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbttClientSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbttClientSearch.setText("Search");

        txtGame.setEditable(false);
        txtGame.setBackground(new java.awt.Color(204, 204, 204));
        txtGame.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jbttGameSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbttGameSearch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbttGameSearch.setText("Search");

        jlblGame.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblGame.setText("Game :");

        jlblPrice.setBackground(new java.awt.Color(0, 0, 0));
        jlblPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblPrice.setText("Price :");

        jlblState.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblState.setText("State :");

        txtClientDNISearch.setBackground(new java.awt.Color(204, 204, 204));
        txtClientDNISearch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtClientDNISearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientDNISearchActionPerformed(evt);
            }
        });

        txtState.setEditable(false);
        txtState.setBackground(new java.awt.Color(204, 204, 204));
        txtState.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        txtClientNameSurname.setEditable(false);
        txtClientNameSurname.setBackground(new java.awt.Color(204, 204, 204));
        txtClientNameSurname.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtPrice.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jlblTable.setBackground(new java.awt.Color(0, 0, 0));
        jlblTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N

        jlblClientDebts.setBackground(new java.awt.Color(0, 0, 0));
        jlblClientDebts.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlblClientDebts.setText("Client debts :");

        txtDebts.setEditable(false);
        txtDebts.setBackground(new java.awt.Color(204, 204, 204));
        txtDebts.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jlbDaysToRent.setBackground(new java.awt.Color(255, 255, 255));
        jlbDaysToRent.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jlbDaysToRent.setText(" Days to rent :");
        jlbDaysToRent.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtDaysToRent.setBackground(new java.awt.Color(204, 204, 204));
        txtDaysToRent.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtDaysToRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysToRentActionPerformed(evt);
            }
        });

        jbttConfirmDaysToRent.setBackground(new java.awt.Color(255, 255, 255));
        jbttConfirmDaysToRent.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbttConfirmDaysToRent.setText(" Confirm");

        javax.swing.GroupLayout jpnlMenuLayout = new javax.swing.GroupLayout(jpnlMenu);
        jpnlMenu.setLayout(jpnlMenuLayout);
        jpnlMenuLayout.setHorizontalGroup(
            jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMenuLayout.createSequentialGroup()
                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jlblTable))
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlblClientDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientDNISearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbttClientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jlblGameName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jbttGameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpnlMenuLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jlblClientDebts))
                                .addComponent(jlblClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbDaysToRent)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addComponent(txtDaysToRent, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbttConfirmDaysToRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtClientNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDebts, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblState, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblGame, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGame, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        jpnlMenuLayout.setVerticalGroup(
            jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMenuLayout.createSequentialGroup()
                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblClientDNI))
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClientDNISearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbttClientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblGameName)))
                            .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbttGameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlMenuLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtGameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblState, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jlblTable))
                    .addGroup(jpnlMenuLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblClient, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblClientDebts)
                            .addComponent(txtDebts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDaysToRent)
                            .addComponent(txtDaysToRent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttConfirmDaysToRent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpnlTable.setBackground(new java.awt.Color(255, 255, 255));
        jpnlTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlTable.setLayout(new java.awt.BorderLayout());

        tableRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Game", "Client", "Sale", "Return"
            }
        ));
        jScrollPane1.setViewportView(tableRent);

        jpnlTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jpnlDown.setBackground(new java.awt.Color(51, 0, 0));
        jpnlDown.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbttCancel.setBackground(new java.awt.Color(255, 255, 255));
        jbttCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbttCancel.setText("CANCEL");
        jbttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttCancelActionPerformed(evt);
            }
        });

        jbttConfirm.setBackground(new java.awt.Color(255, 255, 255));
        jbttConfirm.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbttConfirm.setText("CONFIRM ");

        jbttTotal.setBackground(new java.awt.Color(255, 255, 255));
        jbttTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbttTotal.setText("TOTAL :");

        txtTotalCost.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalCost.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnlDownLayout = new javax.swing.GroupLayout(jpnlDown);
        jpnlDown.setLayout(jpnlDownLayout);
        jpnlDownLayout.setHorizontalGroup(
            jpnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbttTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbttCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbttConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jpnlDownLayout.setVerticalGroup(
            jpnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDownLayout.createSequentialGroup()
                .addGroup(jpnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlDownLayout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(jpnlDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbttCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttTotal)))
                    .addGroup(jpnlDownLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtTotalCost)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method in charge of calculating the total cost of the rent.
     *
     * @return the total cost of the rent
     */
    public double calculateTotalCost() {
        double total = 0;
        if (isReady()) {
            total = game.getPrice() * this.getDaysToRent();
        }
        return total;
    }

    /**
     * Method in charge of verifying if the fields are ready to make the rent.
     * Terms: -If the game has been selected. -If the client has been selected.
     * -If the date has been selected.
     *
     * @return
     */
    public boolean isReady() {
        if (this.game == null) {
            JOptionPane.showMessageDialog(null, "Enter a game that will be rented");
            return false;
        } else if (this.client == null) {
            JOptionPane.showMessageDialog(null, "You must enter a client");
            return false;
        } else if (this.returnDate == null) {
            JOptionPane.showMessageDialog(null, "Enter the days it will be rented");
            return false;
        }
        return true;
    }

    /**
     * Method in charge of cleaning the text fields.
     */
    public void clean() {
        this.game = null;
        this.daysToRent = 0;
        this.returnDate = null;
        this.txtTotalCost.setText(null);
        this.txtState.setText(null);
        this.txtPrice.setText(null);
        this.txtGameSearch.setText(null);
        this.txtDaysToRent.setText(null);
        this.txtGame.setText(null);
    }

    /**
     * Method in charge of returning the current date.
     *
     * @return the current date.
     */
    public Date getCurrentDate() {
        Calendar calendar = Calendar.getInstance();
        Date date = new Date(calendar.getTimeInMillis());
        return date;
    }

    /**
     *
     * Method in charge of calculating the day of return.
     *
     * @param days days the game will be for rent.
     * @return The game return date
     */
    public Date setReturnDate(int days) {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DAY_OF_YEAR, days);
        Date date = new Date(calendar.getTimeInMillis());
        this.returnDate = date;
        return date;
    }

    //GETTERS AND SETTERS.
    
    public void setClient(Client client) {
        this.client = client;
        this.clientSelected = client.getSurname();
        this.update();
    }

    public Game getGame() {
        return game;
    }

    public Client getClient() {
        return client;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public Date getReturnDate() {
        return this.returnDate;
    }

    public int getDaysToRent() {
        return this.daysToRent;
    }

    public void setDaysToRent(int days) {
        this.daysToRent = days;
    }

    public double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }

    private void txtGameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameSearchActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtClientDNISearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientDNISearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientDNISearchActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void jbttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttCancelActionPerformed

    private void jbttBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttBackActionPerformed

    private void txtDaysToRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysToRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysToRentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbttBack;
    public javax.swing.JButton jbttCancel;
    public javax.swing.JButton jbttClientSearch;
    public javax.swing.JButton jbttConfirm;
    public javax.swing.JButton jbttConfirmDaysToRent;
    public javax.swing.JButton jbttGameSearch;
    public javax.swing.JButton jbttTotal;
    private javax.swing.JLabel jlbDaysToRent;
    private javax.swing.JLabel jlblClient;
    private javax.swing.JLabel jlblClientDNI;
    private javax.swing.JLabel jlblClientDebts;
    private javax.swing.JLabel jlblGame;
    private javax.swing.JLabel jlblGameName;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblState;
    public javax.swing.JLabel jlblTable;
    private javax.swing.JPanel jpnlDown;
    private javax.swing.JPanel jpnlMenu;
    private javax.swing.JPanel jpnlTable;
    private javax.swing.JPanel jpnlUp;
    private javax.swing.JTable tableRent;
    public javax.swing.JTextField txtClientDNISearch;
    public javax.swing.JTextField txtClientNameSurname;
    public javax.swing.JTextField txtDaysToRent;
    public javax.swing.JTextField txtDebts;
    public javax.swing.JTextField txtGame;
    public javax.swing.JTextField txtGameSearch;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtState;
    public javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
