/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.gameshop.view.game;


import java.awt.Dimension;
import py.edu.fiuni.gameshop.controller.game.GameFormController;
import py.edu.fiuni.gameshop.dao.mysql.MySQLGameDAO;

/*
 *UNIVERSIDAD NACIONAL DE ITAPUA
 *PROJECT GAMESHOP
 *
 * 2020 - SEGUNDO SEMESTRE
 *
 *  Jorge Tyrakowski & Pamela Horn
 */

/**
 * Method that contains the form panel to add a video game.
 */
public class FrmGame extends javax.swing.JFrame {

    private GameFormController controller = null;
    private MySQLGameDAO dao = null;
    private PanelGames panel = null;
    
    /**
     * Constructor where the necessary for the use of the panel is initialized.
     */
    public FrmGame(PanelGames panel, MySQLGameDAO dao) {
        initComponents();
        this.setSize(new Dimension(900,620));
        this.setPreferredSize(new Dimension(900,620));
        this.setResizable(false);
        setTitle("Game Form");
        setLocationRelativeTo(null);
        this.panel = panel;
        this.dao = dao;
        controller = new GameFormController(panel, this, dao);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JPanel();
        jlbCompany = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbGenre = new javax.swing.JLabel();
        jlbDescription = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtConsole = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jpnUp = new javax.swing.JPanel();
        jlbGameForm = new javax.swing.JLabel();
        jplDown = new javax.swing.JPanel();
        jbttClear = new javax.swing.JButton();
        jbttSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 620));

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpnPrincipal.setPreferredSize(new java.awt.Dimension(1280, 400));

        jlbCompany.setBackground(new java.awt.Color(0, 0, 0));
        jlbCompany.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jlbCompany.setText("Company :");

        jlbName.setBackground(new java.awt.Color(0, 0, 0));
        jlbName.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jlbName.setText("Name : ");

        jlbGenre.setBackground(new java.awt.Color(0, 0, 0));
        jlbGenre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jlbGenre.setText("Genre :");

        jlbDescription.setBackground(new java.awt.Color(0, 0, 0));
        jlbDescription.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jlbDescription.setText("Description :");

        jlbPrice.setBackground(new java.awt.Color(0, 0, 0));
        jlbPrice.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jlbPrice.setText("Price :");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel2.setText("Console :");

        txtName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtConsole.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtCompany.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtGenre.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtDescription.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(jlbName)
                        .addGap(71, 71, 71)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(txtConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(jlbCompany)
                        .addGap(46, 46, 46)
                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jlbGenre)
                        .addGap(46, 46, 46)
                        .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(jlbPrice)
                        .addGap(84, 84, 84)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(jlbDescription)
                        .addGap(29, 29, 29)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbName)
                    .addComponent(jLabel2)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbCompany))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbGenre)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jlbDescription))
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPrice))
                .addGap(3, 3, 3))
        );

        getContentPane().add(jpnPrincipal, java.awt.BorderLayout.CENTER);

        jpnUp.setBackground(new java.awt.Color(60, 0, 0));

        jlbGameForm.setBackground(new java.awt.Color(255, 255, 255));
        jlbGameForm.setFont(new java.awt.Font("Lucida Fax", 1, 70)); // NOI18N
        jlbGameForm.setForeground(new java.awt.Color(255, 255, 255));
        jlbGameForm.setText(" Game Form");

        javax.swing.GroupLayout jpnUpLayout = new javax.swing.GroupLayout(jpnUp);
        jpnUp.setLayout(jpnUpLayout);
        jpnUpLayout.setHorizontalGroup(
            jpnUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnUpLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jlbGameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        jpnUpLayout.setVerticalGroup(
            jpnUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbGameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnUp, java.awt.BorderLayout.PAGE_START);

        jplDown.setBackground(new java.awt.Color(60, 0, 0));
        jplDown.setPreferredSize(new java.awt.Dimension(1280, 100));

        jbttClear.setBackground(new java.awt.Color(255, 255, 255));
        jbttClear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbttClear.setText("CLEAR");

        jbttSave.setBackground(new java.awt.Color(255, 255, 255));
        jbttSave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbttSave.setText("  SAVE  ");

        javax.swing.GroupLayout jplDownLayout = new javax.swing.GroupLayout(jplDown);
        jplDown.setLayout(jplDownLayout);
        jplDownLayout.setHorizontalGroup(
            jplDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplDownLayout.createSequentialGroup()
                .addContainerGap(656, Short.MAX_VALUE)
                .addComponent(jbttClear)
                .addGap(18, 18, 18)
                .addComponent(jbttSave)
                .addGap(33, 33, 33))
        );
        jplDownLayout.setVerticalGroup(
            jplDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDownLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jplDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttClear)
                    .addComponent(jbttSave))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jplDown, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbttClear;
    public javax.swing.JButton jbttSave;
    private javax.swing.JLabel jlbCompany;
    private javax.swing.JLabel jlbDescription;
    private javax.swing.JLabel jlbGameForm;
    private javax.swing.JLabel jlbGenre;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JPanel jplDown;
    private javax.swing.JPanel jpnPrincipal;
    private javax.swing.JPanel jpnUp;
    public javax.swing.JTextField txtCompany;
    public javax.swing.JTextField txtConsole;
    public javax.swing.JTextField txtDescription;
    public javax.swing.JTextField txtGenre;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
