/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.gameshop.view.game;

import java.awt.Color;
import py.edu.fiuni.gameshop.model.Game;

/*
 *UNIVERSIDAD NACIONAL DE ITAPUA
 *PROJECT GAMESHOP
 *
 * 2020 - SEGUNDO SEMESTRE
 *
 *  Jorge Tyrakowski & Pamela Horn
 */

/**
 * Class that contains the information window of a video game
 */
public class GameInfo extends javax.swing.JFrame {

    private Game game = null;

    /**
     * Constructor where the necessary for the use of the panel is initialized.
     */
    public GameInfo(Game game) {
        initComponents();
        setLocationRelativeTo(null);
        this.jlblName.setBackground(new Color(0, 0, 0, 110));

        this.game = game;
        loadInformation();

        this.setVisible(true);

    }

    /**
     * Method in charge of completing the text fields with the information of the video game.
     */
    private void loadInformation() {
        this.jlblGameName.setText(game.getName());
        this.jlblGameGenre.setText(game.getGenre());
        this.jlblGameCompany.setText(game.getCompany());
        this.jlblGamePrice.setText(String.valueOf(game.getPrice()).concat(" $"));
        this.jlblGameState.setText(game.getAvailability());
        this.jlblGameConsole.setText(game.getConsole());
        this.jtxtGameDescription.setText(game.getDescription());
        this.jtxtGameDescription.setLineWrap(true);
        this.jtxtGameDescription.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jpnlCenter = new javax.swing.JPanel();
        jlblName = new javax.swing.JPanel();
        jlblNamee = new javax.swing.JLabel();
        jlblConsole = new javax.swing.JLabel();
        jlblComany = new javax.swing.JLabel();
        jlblGenre = new javax.swing.JLabel();
        jlblDescription = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jlblAvailability = new javax.swing.JLabel();
        jlblGameName = new javax.swing.JLabel();
        jlblGameGenre = new javax.swing.JLabel();
        jlblGameConsole = new javax.swing.JLabel();
        jlblGameCompany = new javax.swing.JLabel();
        jlblGameState = new javax.swing.JLabel();
        jlblGamePrice = new javax.swing.JLabel();
        jscrollGameInfo = new javax.swing.JScrollPane();
        jtxtGameDescription = new javax.swing.JTextArea();
        jlblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 620));

        jpnlPrincipal.setPreferredSize(new java.awt.Dimension(900, 620));
        jpnlPrincipal.setLayout(new java.awt.BorderLayout());

        jpnlCenter.setLayout(null);

        jlblName.setBackground(new java.awt.Color(0, 0, 0));

        jlblNamee.setBackground(new java.awt.Color(153, 153, 153));
        jlblNamee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblNamee.setForeground(new java.awt.Color(255, 255, 255));
        jlblNamee.setText("Name :");

        jlblConsole.setBackground(new java.awt.Color(153, 153, 153));
        jlblConsole.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblConsole.setForeground(new java.awt.Color(255, 255, 255));
        jlblConsole.setText("Console :");

        jlblComany.setBackground(new java.awt.Color(153, 153, 153));
        jlblComany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblComany.setForeground(new java.awt.Color(255, 255, 255));
        jlblComany.setText("Company :");

        jlblGenre.setBackground(new java.awt.Color(153, 153, 153));
        jlblGenre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGenre.setForeground(new java.awt.Color(255, 255, 255));
        jlblGenre.setText("Genre :");

        jlblDescription.setBackground(new java.awt.Color(153, 153, 153));
        jlblDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblDescription.setForeground(new java.awt.Color(255, 255, 255));
        jlblDescription.setText("Description :");

        jlblPrice.setBackground(new java.awt.Color(153, 153, 153));
        jlblPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblPrice.setForeground(new java.awt.Color(255, 255, 255));
        jlblPrice.setText("Price :");

        jlblAvailability.setBackground(new java.awt.Color(153, 153, 153));
        jlblAvailability.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblAvailability.setForeground(new java.awt.Color(255, 255, 255));
        jlblAvailability.setText("Availability :");

        jlblGameName.setBackground(new java.awt.Color(153, 153, 153));
        jlblGameName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGameName.setForeground(new java.awt.Color(255, 255, 255));
        jlblGameName.setText("Name of the Game");

        jlblGameGenre.setBackground(new java.awt.Color(153, 153, 153));
        jlblGameGenre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGameGenre.setForeground(new java.awt.Color(255, 255, 255));
        jlblGameGenre.setText("Genre of the Game");

        jlblGameConsole.setBackground(new java.awt.Color(153, 153, 153));
        jlblGameConsole.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGameConsole.setForeground(new java.awt.Color(255, 255, 255));
        jlblGameConsole.setText("Console of the Game");

        jlblGameCompany.setBackground(new java.awt.Color(153, 153, 153));
        jlblGameCompany.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGameCompany.setForeground(new java.awt.Color(255, 255, 255));
        jlblGameCompany.setText("Company of the Game");

        jlblGameState.setBackground(new java.awt.Color(153, 153, 153));
        jlblGameState.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGameState.setForeground(new java.awt.Color(255, 255, 255));
        jlblGameState.setText("State of the Game");

        jlblGamePrice.setBackground(new java.awt.Color(153, 153, 153));
        jlblGamePrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblGamePrice.setForeground(new java.awt.Color(0, 182, 45));
        jlblGamePrice.setText("Price of the game");

        jtxtGameDescription.setEditable(false);
        jtxtGameDescription.setColumns(20);
        jtxtGameDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtxtGameDescription.setRows(5);
        jtxtGameDescription.setWrapStyleWord(true);
        jscrollGameInfo.setViewportView(jtxtGameDescription);

        javax.swing.GroupLayout jlblNameLayout = new javax.swing.GroupLayout(jlblName);
        jlblName.setLayout(jlblNameLayout);
        jlblNameLayout.setHorizontalGroup(
            jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlblNameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlblNameLayout.createSequentialGroup()
                        .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlblNameLayout.createSequentialGroup()
                                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblNamee)
                                    .addComponent(jlblGenre))
                                .addGap(18, 18, 18)
                                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblGameGenre)
                                    .addComponent(jlblGameName)))
                            .addGroup(jlblNameLayout.createSequentialGroup()
                                .addComponent(jlblAvailability)
                                .addGap(18, 18, 18)
                                .addComponent(jlblGameState)))
                        .addGap(169, 169, 169)
                        .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlblNameLayout.createSequentialGroup()
                                .addComponent(jlblConsole)
                                .addGap(27, 27, 27)
                                .addComponent(jlblGameConsole))
                            .addGroup(jlblNameLayout.createSequentialGroup()
                                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblComany)
                                    .addComponent(jlblPrice))
                                .addGap(18, 18, 18)
                                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblGameCompany)
                                    .addComponent(jlblGamePrice)))))
                    .addGroup(jlblNameLayout.createSequentialGroup()
                        .addComponent(jlblDescription)
                        .addGap(26, 26, 26)
                        .addComponent(jscrollGameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jlblNameLayout.setVerticalGroup(
            jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlblNameLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNamee)
                    .addComponent(jlblGameName)
                    .addComponent(jlblConsole)
                    .addComponent(jlblGameConsole))
                .addGap(37, 37, 37)
                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGenre)
                    .addComponent(jlblGameGenre)
                    .addComponent(jlblComany)
                    .addComponent(jlblGameCompany))
                .addGap(34, 34, 34)
                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAvailability)
                    .addComponent(jlblPrice)
                    .addComponent(jlblGameState)
                    .addComponent(jlblGamePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jlblNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlblNameLayout.createSequentialGroup()
                        .addComponent(jlblDescription)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlblNameLayout.createSequentialGroup()
                        .addComponent(jscrollGameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        jpnlCenter.add(jlblName);
        jlblName.setBounds(30, 90, 840, 470);

        jlblWallpaper.setBackground(new java.awt.Color(153, 153, 153));
        jlblWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        jlblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/edu/fiuni/gameshop/view/icons/icon5.jpg"))); // NOI18N
        jlblWallpaper.setText("jLabel1");
        jpnlCenter.add(jlblWallpaper);
        jlblWallpaper.setBounds(0, 0, 900, 660);

        jpnlPrincipal.add(jpnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblAvailability;
    private javax.swing.JLabel jlblComany;
    private javax.swing.JLabel jlblConsole;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblGameCompany;
    private javax.swing.JLabel jlblGameConsole;
    private javax.swing.JLabel jlblGameGenre;
    private javax.swing.JLabel jlblGameName;
    private javax.swing.JLabel jlblGamePrice;
    private javax.swing.JLabel jlblGameState;
    private javax.swing.JLabel jlblGenre;
    private javax.swing.JPanel jlblName;
    private javax.swing.JLabel jlblNamee;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblWallpaper;
    private javax.swing.JPanel jpnlCenter;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JScrollPane jscrollGameInfo;
    private javax.swing.JTextArea jtxtGameDescription;
    // End of variables declaration//GEN-END:variables
}
