/**
 *UNIVERSIDAD NACIONAL DE ITAPUA
 *PROJECT GAMESHOP
 *
 * 2020 - SEGUNDO SEMESTRE
 *
 *  Jorge Tyrakowski & Pamela Horn
 * */
package py.edu.fiuni.gameshop.view.client;

import javax.swing.JTextField;

/**
 *
 * Class used to get a Panel to log data and display data.
 */
public class ClientLogger extends javax.swing.JPanel {

    /**
     *
     *
     * Creates new form ClientLogger
     */
    public ClientLogger() {
        initComponents();
    }

    /**
     * Set the  text fields jointly editable o not editable.
     * @param editable true or false 
     */
    public void setEditable(boolean editable) {
        this.jtxtDni.setEditable(editable);
        this.jtxtName.setEditable(editable);
        this.jtxtSurname.setEditable(editable);
        this.jtxtAdress.setEditable(editable);
        this.jtxtEmail.setEditable(editable);
        this.jtxtNumber.setEditable(editable);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblName = new javax.swing.JLabel();
        jlblSurname = new javax.swing.JLabel();
        jlblDni = new javax.swing.JLabel();
        jlblAdress = new javax.swing.JLabel();
        jlblEmail = new javax.swing.JLabel();
        jlblNumber = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtDni = new javax.swing.JTextField();
        jtxtAdress = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtNumber = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jlblName.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblName.setText("Name:");

        jlblSurname.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblSurname.setText("Surname: ");

        jlblDni.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblDni.setText("DNI:");

        jlblAdress.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblAdress.setText("Adress:");

        jlblEmail.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblEmail.setText("E-mail:");

        jlblNumber.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jlblNumber.setText("Phone number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblSurname)
                                    .addComponent(jlblEmail)
                                    .addComponent(jlblAdress))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlblDni)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlblName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jlblNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSurname))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblAdress))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNumber)
                    .addComponent(jtxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //GETTERS AND SETTERS 
    
    
    public JTextField getJtxtAdress() {
        return jtxtAdress;
    }

    public void setJtxtAdress(JTextField jtxtAdress) {
        this.jtxtAdress = jtxtAdress;
    }

    public JTextField getJtxtDni() {
        return jtxtDni;
    }

    public void setJtxtDni(JTextField jtxtDni) {
        this.jtxtDni = jtxtDni;
    }

    public JTextField getJtxtEmail() {
        return jtxtEmail;
    }

    public void setJtxtEmail(JTextField jtxtEmail) {
        this.jtxtEmail = jtxtEmail;
    }

    public JTextField getJtxtName() {
        return jtxtName;
    }

    public void setJtxtName(JTextField jtxtName) {
        this.jtxtName = jtxtName;
    }

    public JTextField getJtxtNumber() {
        return jtxtNumber;
    }

    public void setJtxtNumber(JTextField jtxtNumber) {
        this.jtxtNumber = jtxtNumber;
    }

    public JTextField getJtxtSurname() {
        return jtxtSurname;
    }

    public void setJtxtSurname(JTextField jtxtSurname) {
        this.jtxtSurname = jtxtSurname;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblAdress;
    private javax.swing.JLabel jlblDni;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblNumber;
    private javax.swing.JLabel jlblSurname;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtDni;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtNumber;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables

}
